/**
 * Marcas de vehículos presentes en Perú (autos, camiones y comerciales).
 * Orden alfabético para facilitar búsqueda en el autocomplete.
 */
export const VEHICLE_BRANDS_PERU: readonly string[] = [
  'BAIC',
  'BYD',
  'Chevrolet',
  'Changan',
  'Chery',
  'DAF',
  'Dongfeng',
  'FAW',
  'Foton',
  'Freightliner',
  'FUSO',
  'GAC',
  'Hino',
  'Honda',
  'Hyundai',
  'International',
  'Isuzu',
  'IVECO',
  'JAC',
  'Jeep',
  'JMC',
  'Kenworth',
  'Kia',
  'MAN',
  'Mazda',
  'Mercedes-Benz',
  'MG',
  'Mitsubishi',
  'Nissan',
  'Peugeot',
  'Renault',
  'Scania',
  'Shacman',
  'Sinotruk',
  'SsangYong',
  'Subaru',
  'Suzuki',
  'Toyota',
  'VOLKSWAGEN',
  'Volvo',
  'ZX Auto'
] as const;
